### ISSUE TITLE
Train:   0% 

### ISSUE THREAD

**Issue by 760677482** [shariqfarooq123/AdaBins#53]
In the beginning，I noticed that I didn‘t have "pytorch3d",so I used  "pip install pytorch3d"，but it showed an error.then I used"pip unintall pytorch3d"and downloaded it from https://anaconda.org/pytorch3d/pytorch3d/files. But now, when training,it's always "Epoch: 1/25. Loop: Train:   0% 0/11579 [03:37<?, ?it/s]".  I found the program stopped at this line:loss.backward().

What could be the problem?And I am using cuda 9.2 because my Driver version is outdated.looking forword to your help,thanks ！

**Comment by eugenelyj** [comment]
You can try unset the flag of `args.distributed `.

**Comment by shariqfarooq123** [comment]
Please refer to instructions provided [here](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md) to install pytorch3d. 

If you can't install pytorch3d for your driver version, you may also give a try to pytorch3d-nightly.

As @eugenelyj pointed out, try unsetting the distributed flag. You may get a better traceback.

**Comment by libetter0913** [comment]
Hello，I had the same problem. When I ran ‘python train.py args_train_nyu.txt’，The program stops here. Can you help me?
![image](https://user-images.githubusercontent.com/91594047/168235896-44225662-9fdc-4b5e-8040-06d4eb2ac222.png)

**Comment by 9796l** [comment]
> Hello，I had the same problem. When I ran ‘python train.py args_train_nyu.txt’，The program stops here. Can you help me? ![image](https://user-images.githubusercontent.com/91594047/168235896-44225662-9fdc-4b5e-8040-06d4eb2ac222.png)

**Comment by 9796l** [comment]
excuse me,did you solve this problem?

**Comment by zhangbaijin** [comment]
> excuse me,did you solve this problem?

Did you sovle the problem?

**Comment by 9796l** [comment]
我好像是换了个服务器，用了4块显卡的服务器就没有报错了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shariqfarooq123/AdaBins"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月24日(星期五) 上午8:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shariqfarooq123/AdaBins] Train:   0%  (Issue #53)





  
excuse me,did you solve this problem?
  
Did you sovle the problem?

**Comment by zhangbaijin** [comment]
> 我好像是换了个服务器，用了4块显卡的服务器就没有报错了。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "shariqfarooq123/AdaBins" ***@***.***&gt;; 发送时间:&nbsp;2023年3月24日(星期五) 上午8:40 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [shariqfarooq123/AdaBins] Train: 0% (Issue #53) excuse me,did you solve this problem? Did you sovle the problem? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;
我这边用的自己的数据集，raw_image，和depth image。作者说的input.txt是指的哪个文件呢，后面857.47又代表啥意思呢？
`
Traceback (most recent call last):
  File "train.py", line 403, in <module>
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/root/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/root/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/root/autodl-tmp/UDepth-master/train.py", line 109, in main_worker
    experiment_name=args.name, optimizer_state_dict=None)
  File "/root/autodl-tmp/UDepth-master/train.py", line 178, in train
    args) else enumerate(train_loader):
  File "/root/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/miniconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/autodl-tmp/UDepth-master/dataloader.py", line 87, in __getitem__
    focal = float(sample_path.split()[2])
IndexError: list index out of range
`

**Comment by zhangbaijin** [comment]
> 我好像是换了个服务器，用了4块显卡的服务器就没有报错了。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "shariqfarooq123/AdaBins" ***@***.***&gt;; 发送时间:&nbsp;2023年3月24日(星期五) 上午8:40 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [shariqfarooq123/AdaBins] Train: 0% (Issue #53) excuse me,did you solve this problem? Did you sovle the problem? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;
不知道可否加微信咨询一下，我的是SemiMobile

**Comment by jasdkfj** [comment]
> 

focal的问题

**Comment by jasdkfj** [comment]
> > 我好像是换了个服务器，用了4块显卡的服务器就没有报错了。
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "shariqfarooq123/AdaBins" _**@**_._**>; 发送时间: 2023年3月24日(星期五) 上午8:40 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [shariqfarooq123/AdaBins] Train: 0% (Issue #53) excuse me,did you solve this problem? Did you sovle the problem? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > 我这边用的自己的数据集，raw_image，和depth image。作者说的input.txt是指的哪个文件呢，后面857.47又代表啥意思呢？
> > `
> > Traceback (most recent call last):
> > File "train.py", line 403, in 
> > mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
> > File "/root/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
> > return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
> > File "/root/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
> > while not context.join():
> > File "/root/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
> > raise Exception(msg)
> > Exception:
> 
> -- Process 1 terminated with the following error: Traceback (most recent call last): File "/root/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap fn(i, *args) File "/root/autodl-tmp/UDepth-master/train.py", line 109, in main_worker experiment_name=args.name, optimizer_state_dict=None) File "/root/autodl-tmp/UDepth-master/train.py", line 178, in train args) else enumerate(train_loader): File "/root/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in **next** data = self._next_data() File "/root/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data data = self._dataset_fetcher.fetch(index) # may raise StopIteration File "/root/miniconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/root/miniconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/root/autodl-tmp/UDepth-master/dataloader.py", line 87, in **getitem** focal = float(sample_path.split()[2]) IndexError: list index out of range `

focal的问题，你分割的文件里后面肯定没有标focal length in pixels，读不出来就报错了
