### ISSUE TITLE
Potrch version

### ISSUE THREAD

**Issue by Chen-che-w** [shariqfarooq123/AdaBins#8]
The following situation occurred when I ran the code

Traceback (most recent call last):
  File "infer.py", line 158, in <module>
    inferHelper = InferenceHelper()
  File "infer.py", line 85, in __init__
    model, _, _ = model_io.load_checkpoint(pretrained_path, model)
  File "/home/titan2/AdaBins/model_io.py", line 37, in load_checkpoint
    ckpt = torch.load(fpath, map_location='cpu')
  File "/home/titan2/anaconda3/envs/adabins/lib/python3.6/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/titan2/anaconda3/envs/adabins/lib/python3.6/site-packages/torch/serialization.py", line 599, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: ./pretrained/AdaBins_nyu.pt is a zip archive (did you mean to use torch.jit.load()?)

The following situation occurred when I ran the code
After I googled, I knew it was a pytorch version issue
I currently use Pytorch 1.3.1
I want to know what the Pytorch version of the pretrained model is when you are training
Thank you!

**Comment by Rothfeld** [comment]
I have it running on Pytorch 1.7.1

**Comment by shariqfarooq123** [comment]
Code should work fine for Pytorch1.6.0 and above
